### PR TITLE
Fixed #38

### LINKED ISSUE #38: segmentation fault
```
x@192-168-10-195 Inferius-master % ./bundlegen -d 'iPhone10,3' -i '14.6'
Creating Firmware Bundle for iPhone10,3, iOS 14.6
[1] Grabbing decryption keys...
[2] Patching bootchain...
[3] Patching kernel...
[4] Patching ramdisk. This may take a while, please wait...
zsh: segmentation fault  ./bundlegen -d 'iPhone10,3' -i '14.6'
```

### PR DESCRIPTION
**Pull request by vadimszzz**

### CODE REVIEW

**Comment by m1stadev** [comment]
Hi, appreciate the PR!

Couple of comments:
- Is there any need to switch from `bsdiff` to `xdelta3`? Are there benefits to using the latter?
- Not too big on the idea of adding in compiled binaries, as they'd only work for the system they're compiled for (I'm assuming macOS x86?), when Inferius supports (most, if not) all Linux/macOS hosts.
- Could this PR be split up into the various changes that are being done (switch to `xdelta3` for patch format, adding in binaries, and adding in functionality for manually specifying SHSH blobs?)

**Comment by vadimszzz** [comment]
Hi @m1stadev ✌️
- bsdiff always failed with segmentation fault with 100MB dmg files even on my new MacBook Pro, as you can see I added more prints to understand it. Take a look at #38. bsdiff is very hungry to RAM, I replaced it with faster alternative, now it generates new bundles within 1-2 minutes and doesn't fails.
- Yes, it's not a big deal to drop this commit. Better provide binaries for every platform and choice in Python code which to call but I won't implement this.
- I added manually setting BLOBS because futurerestore had fatal issue sending wrong TSS request, I talked to it's main developer and he fixed it with my help: https://github.com/tihmstar/tsschecker/issues/169

Feel free to drop/edit commits or wait until tomorrow when I'll go to office and edit it.

Happy Halloween 🎃🦇

**Comment by m1stadev** [comment]
Any update on splitting the PRs?

**Comment by vadimszzz** [comment]
Sorry I'm busy working at the big project for the next BlackHat USA 🎩

Today would be updated.

**Comment by m1stadev** [comment]
Coming back to this PR as I prepare for an update, I looked at `xdelta3` as a replacement for `bsdiff4`, but in my testing the patches don't seem to generate files that match the original files diffed against. Have you had any success utilizing xdelta3 patches?

**Comment by vadimszzz** [comment]
I don’t believe that xdelta3 algorithm doesn’t work as expected. By the way sorry but I’m out.

**Pull request closed without merging**
